//-------------------------------------------------------
// Autogenerated from 'trader_louis.vmf'
//-------------------------------------------------------
Louis <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.louis,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.louis,
			EntityGroup.SpawnTables.usetarget,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			louis = 
			{
				SpawnInfo =
				{
					classname = "commentary_dummy"
					angles = Vector( 0, 0, 0 )
					EyeHeight = "64"
					HeadPitchPoseParam = "Head_Pitch"
					HeadYawPoseParam = "Head_Yaw"
					LookAtPlayers = "1"
					model = "models/survivors/survivor_manager.mdl"
					StartingAnim = "Idle_Calm_Pistol"
					StartingWeapons = "weapon_pistol"
					targetname = "louis"
					origin = Vector( 0, 0, 0 )
				}
			}
			usetarget = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "louis"
					origin = Vector( 0, 0, 0 )
					targetname = "usetarget"
					vscripts = "usetargets/trader_louis"
				}
			}
		} // SpawnTables
	} // EntityGroup
} // Louis

RegisterEntityGroup( "Louis", Louis )
