//-------------------------------------------------------
// Autogenerated from 'trader_melee.vmf'
//-------------------------------------------------------
Melee <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.crowbar,
			EntityGroup.SpawnTables.frying_pan,
			EntityGroup.SpawnTables.tonfa,
			EntityGroup.SpawnTables.machete,
			EntityGroup.SpawnTables.katana,
			EntityGroup.SpawnTables.fireaxe,
			EntityGroup.SpawnTables.cricket_bat,
			EntityGroup.SpawnTables.baseball_bat,
			EntityGroup.SpawnTables.electric_guitar,
			EntityGroup.SpawnTables.golfclub,
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.unnamed1,
			EntityGroup.SpawnTables.unnamed2,
			EntityGroup.SpawnTables.unnamed3,
			EntityGroup.SpawnTables.unnamed4,
			EntityGroup.SpawnTables.unnamed5,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.baseball_bat,
			EntityGroup.SpawnTables.crowbar,
			EntityGroup.SpawnTables.unnamed5,
			EntityGroup.SpawnTables.unnamed4,
			EntityGroup.SpawnTables.unnamed3,
			EntityGroup.SpawnTables.unnamed2,
			EntityGroup.SpawnTables.unnamed1,
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.cricket_bat,
			EntityGroup.SpawnTables.katana,
			EntityGroup.SpawnTables.golfclub,
			EntityGroup.SpawnTables.electric_guitar,
			EntityGroup.SpawnTables.tonfa,
			EntityGroup.SpawnTables.frying_pan,
			EntityGroup.SpawnTables.machete,
			EntityGroup.SpawnTables.fireaxe,
			EntityGroup.SpawnTables.usetarget,
			EntityGroup.SpawnTables.usetarget1,
			EntityGroup.SpawnTables.usetarget2,
			EntityGroup.SpawnTables.usetarget3,
			EntityGroup.SpawnTables.usetarget4,
			EntityGroup.SpawnTables.usetarget5,
			EntityGroup.SpawnTables.usetarget6,
			EntityGroup.SpawnTables.usetarget7,
			EntityGroup.SpawnTables.usetarget8,
			EntityGroup.SpawnTables.usetarget9,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			crowbar = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( -0.5, 270, -90 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/weapons/melee/w_crowbar.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "crowbar"
					origin = Vector( -54, 16, 20 )
				}
			}
			frying_pan = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( -0.5, 270, -90 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/weapons/melee/w_frying_pan.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "frying_pan"
					origin = Vector( -8, 16, 21 )
				}
			}
			tonfa = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( -0.5, 270, -90 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/weapons/melee/w_tonfa.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "tonfa"
					origin = Vector( 35, 21, 20 )
				}
			}
			machete = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( -0.5, 270, -90 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/weapons/melee/w_machete.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "machete"
					origin = Vector( 33, 8, 20 )
				}
			}
			katana = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( -0.5, 270, -90 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/weapons/melee/w_katana.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "katana"
					origin = Vector( 33, -4, 20 )
				}
			}
			fireaxe = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( -0.5, 270, -90 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/weapons/melee/w_fireaxe.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "fireaxe"
					origin = Vector( -8, -5, 20 )
				}
			}
			cricket_bat = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( -0.5, 270, -90 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/weapons/melee/w_cricket_bat.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "cricket_bat"
					origin = Vector( -49, -5, 20 )
				}
			}
			baseball_bat = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 90, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/weapons/melee/w_bat.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "baseball_bat"
					origin = Vector( -59, -21, 20 )
				}
			}
			electric_guitar = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( -0.5, 270, 90 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/weapons/melee/w_electric_guitar.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "electric_guitar"
					origin = Vector( 5, -21, 20 )
				}
			}
			golfclub = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( -0.5, 270, 90 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/weapons/melee/w_golfclub.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "golfclub"
					origin = Vector( 57, -21, 20 )
				}
			}
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 90, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_debris/wood_board05a.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					origin = Vector( 1, 24, 18 )
				}
			}
			unnamed1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 90, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_debris/wood_board05a.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					origin = Vector( 1, 8, 18 )
				}
			}
			unnamed2 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 90, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_debris/wood_board05a.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					origin = Vector( 1, -8, 18 )
				}
			}
			unnamed3 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 90, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_debris/wood_board05a.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					origin = Vector( 1, -24, 18 )
				}
			}
			unnamed4 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_interiors/sawhorse.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					origin = Vector( -54, 0, -20 )
				}
			}
			unnamed5 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_interiors/sawhorse.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					origin = Vector( 55, 0, -20 )
				}
			}
			usetarget = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "crowbar"
					origin = Vector( -54, 16, 20 )
					targetname = "usetarget"
					vscripts = "usetargets/trader_crowbar"
				}
			}
			usetarget1 = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "frying_pan"
					origin = Vector( -8, 16, 22 )
					targetname = "usetarget1"
					vscripts = "usetargets/trader_frying_pan"
				}
			}
			usetarget2 = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "tonfa"
					origin = Vector( 35, 21, 22 )
					targetname = "usetarget2"
					vscripts = "usetargets/trader_tonfa"
				}
			}
			usetarget3 = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "machete"
					origin = Vector( 33, 8, 22 )
					targetname = "usetarget3"
					vscripts = "usetargets/trader_machete"
				}
			}
			usetarget4 = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "katana"
					origin = Vector( 33, -4, 20 )
					targetname = "usetarget4"
					vscripts = "usetargets/trader_katana"
				}
			}
			usetarget5 = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "fireaxe"
					origin = Vector( -8, -5, 20 )
					targetname = "usetarget5"
					vscripts = "usetargets/trader_fireaxe"
				}
			}
			usetarget6 = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "cricket_bat"
					origin = Vector( -49, -5, 20 )
					targetname = "usetarget6"
					vscripts = "usetargets/trader_cricket_bat"
				}
			}
			usetarget7 = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "baseball_bat"
					origin = Vector( -59, -21, 20 )
					targetname = "usetarget7"
					vscripts = "usetargets/trader_baseball_bat"
				}
			}
			usetarget8 = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "electric_guitar"
					origin = Vector( 5, -21, 20 )
					targetname = "usetarget8"
					vscripts = "usetargets/trader_electric_guitar"
				}
			}
			usetarget9 = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "golfclub"
					origin = Vector( 57, -21, 20 )
					targetname = "usetarget9"
					vscripts = "usetargets/trader_golfclub"
				}
			}
		} // SpawnTables
	} // EntityGroup
} // Melee

RegisterEntityGroup( "Melee", Melee )
